# api deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: hasancutcu/api
---
# api service
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  ports:
    - name: api-port
      protocol: TCP
      port: 4000
      targetPort: 4000
